version: "3.9"

services:
  businessprod:
    image: magnusandersen/business-app:delivery

  app-database-2:
      image: mysql
      restart: always
      volumes:
        - ./db/data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: MY_S€cr€t_P@ssw0rD
        MYSQL_DATABASE: GameLib
      ports:
        - 63306:3306

    watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
